org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod
mod.id=mixed_litter
mod.name=Mixed Litter
mod.version=1.1.0
mod.group=dev.tazer.mixed_litter
mod.license=All Rights Reserved
mod.authors=Tazer
mod.description=A data-driven mob variant library that also contains remodels for many of Minecraft's animals

# Minecraft
mc.version=1.21.1
mc.versionRange=[1.21.1]

# NeoForge - https://projects.neoforged.net/neoforged/neoforge
neo.version=21.1.200
neo.versionRange=[21.1.0,)
neo.loaderVersionRange=[4,)

# Parchment
parchment.mappingsVersion=2024.11.17
parchment.minecraftVersion=1.21.1

# Dependencies
deps.jei=19.21.0.247
deps.buzzier_bees=7.0.1
deps.blueprint=8.0.6
